-- Fase 1 — Schema de domínio da biblioteca.
-- IDs em bigint (identidade "by default" para permitir inserir id explícito na migração de dados).
-- Constraints conforme docs/ARQUITETURA.md §3.5.

-- Trigger utilitário para updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Aplica o trigger de updated_at a uma tabela
create or replace function public.attach_set_updated_at(p_table regclass)
returns void language plpgsql as $$
begin
  execute format(
    'create trigger set_updated_at before update on %s
       for each row execute function public.set_updated_at()', p_table);
end;
$$;

-- ============================ Tabelas de referência ============================

create table public.generos (
  id          bigint generated by default as identity primary key,
  nome        text not null unique,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.autores (
  id          bigint generated by default as identity primary key,
  nome        text not null,               -- não único (homônimos permitidos)
  biografia   text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.bibliotecas (
  id          bigint generated by default as identity primary key,
  nome        text not null unique,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.status (
  id          bigint generated by default as identity primary key,
  codigo      text not null unique,        -- 'disponivel' | 'emprestado' | ...
  nome        text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.pessoas (
  id          bigint generated by default as identity primary key,
  nome        text not null,
  cpf         text unique,                 -- opcional; único quando preenchido
  email       text unique,                 -- opcional; único quando preenchido
  telefone    text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint pessoas_cpf_formato check (cpf is null or cpf ~ '^[0-9]{11}$')
);

-- ============================ Catálogo ============================

create table public.livros (
  id            bigint generated by default as identity primary key,
  codigo_livro  text,                      -- texto, opcional, sem unicidade
  nome          text not null,
  resumo        text,
  genero_id     bigint not null references public.generos (id) on delete restrict,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index livros_genero_id_idx on public.livros (genero_id);

create table public.temas (
  id          bigint generated by default as identity primary key,
  livro_id    bigint not null references public.livros (id) on delete cascade,
  nome        text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (livro_id, nome)
);

create table public.livro_autor (
  livro_id  bigint not null references public.livros (id) on delete cascade,
  autor_id  bigint not null references public.autores (id) on delete restrict,
  primary key (livro_id, autor_id)
);
create index livro_autor_autor_id_idx on public.livro_autor (autor_id);

-- ============================ Acervo físico ============================

create table public.exemplares (
  id             bigint generated by default as identity primary key,
  livro_id       bigint not null references public.livros (id) on delete restrict,
  biblioteca_id  bigint not null references public.bibliotecas (id) on delete restrict,
  status_id      bigint not null references public.status (id) on delete restrict,
  numero_tombo   text,                     -- opcional
  data_aquisicao date,                     -- opcional
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index exemplares_livro_id_idx on public.exemplares (livro_id);
create index exemplares_status_id_idx on public.exemplares (status_id);

-- ============================ Circulação ============================

create table public.emprestimos (
  id                       bigint generated by default as identity primary key,
  exemplar_id              bigint not null references public.exemplares (id) on delete restrict,
  pessoa_id                bigint not null references public.pessoas (id) on delete restrict,
  data_emprestimo          date not null default current_date,
  data_prevista_devolucao  date not null,
  data_devolucao           date,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);
create index emprestimos_pessoa_id_idx on public.emprestimos (pessoa_id);
-- No máximo 1 empréstimo em aberto por exemplar
create unique index emprestimos_um_aberto_por_exemplar
  on public.emprestimos (exemplar_id) where data_devolucao is null;

-- ============================ Triggers updated_at ============================

select public.attach_set_updated_at('public.generos');
select public.attach_set_updated_at('public.autores');
select public.attach_set_updated_at('public.bibliotecas');
select public.attach_set_updated_at('public.status');
select public.attach_set_updated_at('public.pessoas');
select public.attach_set_updated_at('public.livros');
select public.attach_set_updated_at('public.temas');
select public.attach_set_updated_at('public.exemplares');
select public.attach_set_updated_at('public.emprestimos');
