-- Fase 1 — ACL (RBAC multi-grupo) + função de verificação + RPCs de circulação.

-- ============================ Tabelas do ACL ============================

create table public.grupos (
  id          bigint generated by default as identity primary key,
  nome        text not null unique,
  descricao   text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.funcionalidades (
  id          bigint generated by default as identity primary key,
  codigo      text not null unique,        -- ex.: 'livro.create'
  nome        text not null,
  categoria   text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.grupo_funcionalidade (
  grupo_id          bigint not null references public.grupos (id) on delete cascade,
  funcionalidade_id bigint not null references public.funcionalidades (id) on delete cascade,
  primary key (grupo_id, funcionalidade_id)
);

create table public.usuario_grupo (
  user_id   uuid not null references auth.users (id) on delete cascade,
  grupo_id  bigint not null references public.grupos (id) on delete cascade,
  primary key (user_id, grupo_id)
);

select public.attach_set_updated_at('public.grupos');
select public.attach_set_updated_at('public.funcionalidades');

-- ============================ Verificação de permissão ============================

-- Verdadeiro se o usuário autenticado possui a funcionalidade (por qualquer um de seus grupos).
create or replace function public.tem_permissao(p_codigo text)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from usuario_grupo ug
    join grupo_funcionalidade gf on gf.grupo_id = ug.grupo_id
    join funcionalidades f       on f.id = gf.funcionalidade_id
    where ug.user_id = auth.uid()
      and f.codigo   = p_codigo
  );
$$;

-- Lista os códigos de funcionalidade do usuário autenticado (para a UI).
create or replace function public.meus_codigos()
returns setof text
language sql
security definer
stable
set search_path = public
as $$
  select distinct f.codigo
  from usuario_grupo ug
  join grupo_funcionalidade gf on gf.grupo_id = ug.grupo_id
  join funcionalidades f       on f.id = gf.funcionalidade_id
  where ug.user_id = auth.uid();
$$;

-- ============================ RPCs de circulação ============================

-- Empresta um exemplar disponível para uma pessoa (transação atômica).
create or replace function public.registrar_emprestimo(
  p_exemplar_id bigint,
  p_pessoa_id   bigint,
  p_data_prevista date default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status_codigo text;
  v_id bigint;
  v_prevista date;
begin
  if not public.tem_permissao('emprestimo.emprestar') then
    raise exception 'Sem permissão para registrar empréstimo' using errcode = '42501';
  end if;

  select s.codigo into v_status_codigo
  from exemplares e
  join status s on s.id = e.status_id
  where e.id = p_exemplar_id;

  if v_status_codigo is null then
    raise exception 'Exemplar % não encontrado', p_exemplar_id using errcode = 'P0002';
  end if;
  if v_status_codigo <> 'disponivel' then
    raise exception 'Exemplar % não está disponível para empréstimo', p_exemplar_id using errcode = 'P0001';
  end if;

  v_prevista := coalesce(p_data_prevista, current_date + 14);

  insert into emprestimos (exemplar_id, pessoa_id, data_emprestimo, data_prevista_devolucao)
  values (p_exemplar_id, p_pessoa_id, current_date, v_prevista)
  returning id into v_id;

  update exemplares
  set status_id = (select id from status where codigo = 'emprestado')
  where id = p_exemplar_id;

  return v_id;
end;
$$;

-- Registra a devolução de um empréstimo em aberto (transação atômica).
create or replace function public.registrar_devolucao(p_emprestimo_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_exemplar_id bigint;
begin
  if not public.tem_permissao('emprestimo.devolver') then
    raise exception 'Sem permissão para registrar devolução' using errcode = '42501';
  end if;

  update emprestimos
  set data_devolucao = current_date
  where id = p_emprestimo_id and data_devolucao is null
  returning exemplar_id into v_exemplar_id;

  if v_exemplar_id is null then
    raise exception 'Empréstimo % não encontrado ou já devolvido', p_emprestimo_id using errcode = 'P0001';
  end if;

  update exemplares
  set status_id = (select id from status where codigo = 'disponivel')
  where id = v_exemplar_id;
end;
$$;

-- As RPCs são chamadas pelo app autenticado.
grant execute on function public.tem_permissao(text) to authenticated;
grant execute on function public.meus_codigos() to authenticated;
grant execute on function public.registrar_emprestimo(bigint, bigint, date) to authenticated;
grant execute on function public.registrar_devolucao(bigint) to authenticated;
